---
title: I have large or sensible data. How should I proceed?
date: '2023-06-21'
description: Describe how to handle large or sensible data files when submitting to
  Computo
tags:
- reproducibility
format:
  html:
    toc: true
page-layout: article
---

## Large data sets

If your submission materials contain files larger than 50MB, **especially data files**, they won’t fit on a git repository as is. For this reason, we encourage you to put your data or any materials you deem necessary on an external “open data” centered repository hub such a [Zenodo](https://zenodo.org/) or [OSF](https://osf.io/).

You could also use any long-term (emphasis on long-term) data repository that is standard in your scientific community (or for a specific type of data/scientific application), and for which it is straight-forward to retrieve the data using a script code/notebook code (we highly encourage to use open platforms, ideally institutionally hosted).

## Sensible data sets

Since the reproducibility of numerical results is a necessary condition for publication in *Computo*, your submissions must include all necessary data (e.g. via Zenodo repositories). However, if you have sensible data (for example, biomedical data that needs to be anonymized), you are invited to contact the editorial committee to explain and justify your position. In any case, we will ask you to make public at least a sample of the original data, and a demonstration of its use in your article for Computo. The results of the analyses carried out on the totality of the data should be made available in the form of a binary file, in order to produce the statistical summaries necessary to illustrate your assertions.
